/**
 * Google Antigravity hooks adapter (experimental).
 *
 * Antigravity uses `.antigravity/rules/*.md` for persistent agent context.
 * There is no tool-level hook primitive yet, so we mirror Cursor's pattern:
 * emit rule files that cascade into the agent's prompt. This is the weakest
 * fidelity tier — documented so users know what they're getting.
 */

import { existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

export const id = 'antigravity';

const RULES_REL_DIR = '.antigravity/rules';
const Topia_PREFIX = 'Topia-';
const AUTO_SIGNATURE = '@protopia/skill-topia hook-dispatch';

export function detect(projectRoot) {
  return existsSync(path.join(projectRoot, '.antigravity'));
}

export async function emit({ preset, projectRoot }) {
  if (preset === 'off') return uninstall({ projectRoot });
  if (preset !== 'off' && preset !== 'strict' && preset !== 'gentle') {
    throw new Error(`antigravity adapter: invalid preset '${preset}'`);
  }

  const mode = preset === 'strict' ? 'BLOCK' : 'WARN';
  const rulesDir = path.join(projectRoot, RULES_REL_DIR);

  const rules = [
    { name: 'preflight', description: 'Run preflight review before any source edit.' },
    { name: 'sentinel', description: 'Security review before shell / infra edits.' },
    { name: 'dependency-doctor', description: 'Dependency audit after manifest edits.' },
  ];

  const files =
    preset === 'off'
      ? []
      : rules.map((r) => ({
          path: path.join(rulesDir, `${Topia_PREFIX}${r.name}.md`),
          content: renderRule(r, mode),
        }));

  const notes =
    preset === 'off'
      ? []
      : [
          'Antigravity support is experimental — rule-injection only, no true hook.',
          `Preset: ${preset} (${mode}). \`completion-gate\` must be invoked manually.`,
        ];

  return { files, notes };
}

export async function uninstall({ projectRoot }) {
  const rulesDir = path.join(projectRoot, RULES_REL_DIR);
  if (!existsSync(rulesDir)) return { files: [], notes: [] };
  const entries = await readdir(rulesDir, { withFileTypes: true });
  const TopiaFiles = entries.filter((e) => e.isFile() && e.name.startsWith(Topia_PREFIX) && e.name.endsWith('.md'));
  const files = [];
  for (const file of TopiaFiles) {
    const abs = path.join(rulesDir, file.name);
    const content = await readFile(abs, 'utf-8');
    if (content.includes(AUTO_SIGNATURE) || content.includes('Topia-managed: true')) {
      files.push({ path: abs, content: null });
    }
  }
  return { files, notes: files.length === 0 ? ['no Topia-managed antigravity rules'] : [] };
}

export async function status(projectRoot) {
  const rulesDir = path.join(projectRoot, RULES_REL_DIR);
  if (!existsSync(rulesDir)) {
    return {
      installed: false,
      preset: null,
      wired: [],
      missing: ['preflight', 'sentinel', 'dependency-doctor'],
      notes: ['no .antigravity/rules directory'],
    };
  }
  const entries = await readdir(rulesDir, { withFileTypes: true });
  const TopiaFiles = entries.filter((e) => e.isFile() && e.name.startsWith(Topia_PREFIX) && e.name.endsWith('.md'));
  const wired = TopiaFiles.map((f) => f.name.replace(Topia_PREFIX, '').replace('.md', ''));
  const expected = ['preflight', 'sentinel', 'dependency-doctor'];
  const missing = expected.filter((s) => !wired.includes(s));

  let preset = null;
  for (const file of TopiaFiles) {
    const content = await readFile(path.join(rulesDir, file.name), 'utf-8');
    if (/^mode: BLOCK$/m.test(content)) {
      preset = 'strict';
      break;
    }
    if (/^mode: WARN$/m.test(content)) preset = preset ?? 'gentle';
  }

  return { installed: TopiaFiles.length > 0, preset, wired, missing, notes: ['experimental — rule-injection only'] };
}

function renderRule(rule, mode) {
  return [
    '---',
    `description: ${rule.description}`,
    'Topia-managed: true',
    `Topia-skill: ${rule.name}`,
    `mode: ${mode}`,
    '---',
    '',
    `# Topia ${rule.name}`,
    '',
    `${rule.description} Mode: ${mode}.`,
    '',
    'Refer to the Topia skill SKILL.md for the full checklist — apply those checks mentally before each matching edit.',
    '',
    `_Auto-generated by \`Topia hooks install\` (${AUTO_SIGNATURE})._`,
    '',
  ].join('\n');
}
